---
0:
  model_code: "resnet"
  lit_code: "sharpen"
  dataset_code: "bmnist"
  spurious_ratio: 0.95
  batch_size: 32
  moments: 5
  epochs: 10
  lr: 0.015
  moment_desc: "baybmnist-baseline"
  model_desc: "bmnist-sharpen"