---
0:
  model_code: "resnet"
  lit_code: "sharpen"
  dataset_code: "bar"
  batch_size: 32
  max_epochs: 19
  optim: "sgd"
  lr: 0.015
  moments: 10
  moment_desc: "baybar-baseline"
  model_desc: "bar-sharpen"